apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-example
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - ingresses
  - deployments
  - services
  - jobs
  verbs:
  - list
  - watch
  - get
  - create
  - delete
  - deletecollection
  - patch
  - update